/* Generated By:JJTree&JavaCC: Do not edit this line. JavadocParserConstants.java */
package de.gulden.util.javasource.jjt;

public interface JavadocParserConstants {

  int EOF = 0;
  int EOL = 4;
  int STAR = 5;
  int SLASH = 6;
  int DOCSTART = 7;
  int DOCEND = 8;
  int WORD = 9;
  int TAG_AUTHOR = 10;
  int TAG_DEPRECATED = 11;
  int TAG_EXCEPTION = 12;
  int TAG_PARAM = 13;
  int TAG_RETURN = 14;
  int TAG_SEE = 15;
  int TAG_SINCE = 16;
  int TAG_THROWS = 17;
  int TAG_VERSION = 18;
  int TAG_ID = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"*\"",
    "\"/\"",
    "<DOCSTART>",
    "\"*/\"",
    "<WORD>",
    "\"@author\"",
    "\"@deprecated\"",
    "\"@exception\"",
    "\"@param\"",
    "\"@return\"",
    "\"@see\"",
    "\"@since\"",
    "\"@throws\"",
    "\"@version\"",
    "\"@id\"",
  };

}
