/* Generated By:JJTree: Do not edit this line. /e/projects/beautyj/src/de/gulden/util/javasource/jjt/JavadocParserTreeConstants.java */

package de.gulden.util.javasource.jjt;

public interface JavadocParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTDESCRIPTION = 2;
  public int JJTLINE = 3;
  public int JJTWORD = 4;
  public int JJTTAG = 5;
  public int JJTTAGITEM = 6;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Description",
    "Line",
    "Word",
    "Tag",
    "TagItem",
  };
}
