/* Generated By:JJTree: Do not edit this line. /tmp/make/beautyJ-1_1/src/beautyj/de/gulden/util/javasource/jjt/ParserTreeConstants.java */

package de.gulden.util.javasource.jjt;

public interface ParserTreeConstants
{
  public int JJT_SOURCE = 0;
  public int JJT_PACKAGE = 1;
  public int JJT_IMPORT = 2;
  public int JJT_PACKAGEIMPORT = 3;
  public int JJTVOID = 4;
  public int JJT_CLASS = 5;
  public int JJT_MODIFIER = 6;
  public int JJT_NAME = 7;
  public int JJT_SUPERCLASS = 8;
  public int JJT_INNERCLASS = 9;
  public int JJT_INTERFACE = 10;
  public int JJT_INNERINTERFACE = 11;
  public int JJT_FIELD = 12;
  public int JJT_FIELDVAR = 13;
  public int JJT_CODE = 14;
  public int JJT_METHOD = 15;
  public int JJT_THROWS = 16;
  public int JJT_PARAMETER = 17;
  public int JJT_FINAL = 18;
  public int JJT_CONSTRUCTOR = 19;
  public int JJT_INITIALIZER = 20;
  public int JJT_STATIC = 21;
  public int JJT_TYPE = 22;
  public int JJT_PRIMITIVE = 23;
  public int JJT_IMPLEMENTS = 24;
  public int JJT_ISARRAY = 25;
  public int JJT_IDENTIFIER = 26;
  public int JJT_DOT = 27;
  public int JJT_PUBLIC = 28;
  public int JJT_PROTECTED = 29;
  public int JJT_PRIVATE = 30;
  public int JJT_ABSTRACT = 31;
  public int JJT_SYNCHRONIZED = 32;
  public int JJT_TRANSIENT = 33;
  public int JJT_VOLATILE = 34;
  public int JJT_STRICTFP = 35;
  public int JJT_NATIVE = 36;


  public String[] jjtNodeName = {
    "_SOURCE",
    "_PACKAGE",
    "_IMPORT",
    "_PACKAGEIMPORT",
    "void",
    "_CLASS",
    "_MODIFIER",
    "_NAME",
    "_SUPERCLASS",
    "_INNERCLASS",
    "_INTERFACE",
    "_INNERINTERFACE",
    "_FIELD",
    "_FIELDVAR",
    "_CODE",
    "_METHOD",
    "_THROWS",
    "_PARAMETER",
    "_FINAL",
    "_CONSTRUCTOR",
    "_INITIALIZER",
    "_STATIC",
    "_TYPE",
    "_PRIMITIVE",
    "_IMPLEMENTS",
    "_ISARRAY",
    "_IDENTIFIER",
    "_DOT",
    "_PUBLIC",
    "_PROTECTED",
    "_PRIVATE",
    "_ABSTRACT",
    "_SYNCHRONIZED",
    "_TRANSIENT",
    "_VOLATILE",
    "_STRICTFP",
    "_NATIVE",
  };
}
